name: Tag
on: 
  create:
    tags:
      - v*
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checkout source code
      uses: actions/checkout@v1
    - name: Get Branch
      run: |
        raw=$(git branch -r --contains ${{ github.ref }})
        branch=${raw##*/}
        echo "BRANCH=$branch" >> $GITHUB_ENV
    - name: Get Branch VV
      run: |
#        GIT_BRANCH_TAG=${{ env.BRANCH }}
#        echo whwhwhw---$GIT_BRANCH_TAG
#        export $GIT_BRANCH_TAG
        sh .github/workflows/pushevent.sh
      env:
        GIT_BRANCH_TAG: ${{ env.BRANCH }}
    - run: echo ${{ env.BRANCH }}
